import './components/tabs'
import '../../vendor/digitalbiblesociety/shin/src/resources/js/components/i18n'
import '../../vendor/digitalbiblesociety/shin/src/resources/js/components/search'
import '../../vendor/digitalbiblesociety/shin/src/resources/js/components/modal'
import '../../vendor/digitalbiblesociety/shin/src/resources/js/components/dataTables'
